name: Update Google Auth Redirect URI on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  update-redirect-uri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Vercel Preview URL
        id: vercel_preview_url
        uses: zentered/vercel-preview-url@v1
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }} # Optional: add if your project is under a Vercel team
          vercel_project_name: ${{ secrets.VERCEL_PROJECT_NAME }} # Optional but recommended: add your project name from Vercel

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Update Google OAuth Client Redirect URIs'
        run: |
          set -e
          CLIENT_ID="${{ secrets.GCP_OAUTH_CLIENT_ID }}"
          PREVIEW_URL="${{ steps.vercel_preview_url.outputs.preview_url }}"

          if [[ -z "$PREVIEW_URL" ]]; then
            echo "Failed to get Vercel preview URL. Skipping update."
            exit 0 # Exit successfully to not block PR
          fi

          # The URL from the action includes 'https://'
          NEW_REDIRECT_URI="${PREVIEW_URL}/api/auth/callback/google"

          echo "Fetching existing redirect URIs for client $CLIENT_ID..."

          # This command might fail if the client has never had any URIs set.
          # We get the full client JSON and parse from it.
          CLIENT_JSON=$(gcloud iap oauth-clients describe "$CLIENT_ID" --format="json")
          EXISTING_URIS_ARRAY=$(echo "$CLIENT_JSON" | jq -c '.redirectUris // []')

          echo "Existing URIs: $EXISTING_URIS_ARRAY"

          UPDATED_URIS_ARRAY=$(echo "$EXISTING_URIS_ARRAY" | jq -c --arg uri "$NEW_REDIRECT_URI" '(. + [$uri]) | unique')
          UPDATED_URIS_STRING=$(echo "$UPDATED_URIS_ARRAY" | jq -r '.[]' | paste -sd "," -)

          echo "New redirect URI to add: $NEW_REDIRECT_URI"
          echo "Updating OAuth client with new list of URIs..."

          gcloud iap oauth-clients update "$CLIENT_ID" --redirect-uris="$UPDATED_URIS_STRING"

          echo "Successfully updated redirect URIs."
